### ISSUE TITLE
where to find tumblr/thrift and tumblr/net packages?

### ISSUE THREAD

**Issue by wanyisunflower** [mindreframer/golang-stuff#14]
I saw the code golang-stuff/github.com/tumblr/gocircuit/src/tumblr/scribe/server.go, it imported "tumblr/encoding/thrift" "tumblr/net/scribe/thrift/fb303" "tumblr/net/scribe/thrift/scribe" however, there are no such folders in anywhere, can anyone help?

**Comment by mindreframer** [comment]
I honestly dont know... It is just a copy from the original repo, maybe you'd have more luck asking directly there? 

https://github.com/tumblr/gocircuit

Petar Maymounkov would probably be able to answer you: 
https://github.com/petar 


Good luck!
