### ISSUE TITLE
psnotify can't work on Darwin platform

### ISSUE THREAD

**Issue by cyongxue** [mindreframer/golang-stuff#16]
for _, ev := range events[:n] {
			pid := int(ev.Ident)

			switch ev.Fflags {
			case syscall.NOTE_FORK:
				fmt.Println(time.Now().Format("2006-01-02 15:04:05"), "NOTE_FORK:", ev)
				w.Fork <- &ProcEventFork{ParentPid: pid}
			case syscall.NOTE_EXEC:
				fmt.Println(time.Now().Format("2006-01-02 15:04:05"), "NOTE_EXEC:", ev)
				w.Exec <- &ProcEventExec{Pid: pid}
			case syscall.NOTE_EXIT:
				fmt.Println(time.Now().Format("2006-01-02 15:04:05"), "NOTE_EXIT:", ev)
				w.RemoveWatch(pid)
				w.Exit <- &ProcEventExit{Pid: pid}
		}

on Darwin platform，because can't get child pid, then can't work on.

**Comment by mindreframer** [comment]
@cyongxue  please open the issue on the original repository (https://github.com/jondot/gosigar), this is just vendored from it. 

Thx for understanding!
